name: Katabump Auto Renew

on:
  schedule:
    - cron: '17 1 2-30/2 * *'
  workflow_dispatch: # 允许手动触发

jobs:
  renew:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    
    steps:
      # =======================================================
      # 替换后的代码块：拉取私有仓库
      - name: 拉取私有仓库
        uses: actions/checkout@v5
        with:
          repository: andyzhouyang198611/katabump
          token: ${{ secrets.REPO_TOKEN }}
          path: .  # 拉到根目录
      # =======================================================
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          npm install
          npx playwright install-deps chrome
          
      - name: Run Renew Script
        env:
          USERS_JSON: ${{ secrets.USERS_JSON }}
          HTTP_PROXY: ${{ secrets.HTTP_PROXY }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" node action_renew.js

      - name: Upload Screenshots
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: screenshots
          path: screenshots/
